pub const WINDOW_HEIGHT: u32 = 32;
pub const RESERVE_SIZE: [u64; 4] = [0, 0, 32, 0];
pub const MENU_WIDTH: u16 = 400;
pub const MENU_HEIGHT: u16 = MENU_WIDTH;
pub const NET_WM_WINDOW_TYPE_DESKTOP: &str = "_NET_WM_WINDOW_TYPE_DESKTOP";
pub const NET_WM_WINDOW_TYPE_DIALOG: &str = "_NET_WM_WINDOW_TYPE_DIALOG";
pub const NET_WM_WINDOW_TYPE_POPUP_MENU: &str = "_NET_WM_WINDOW_TYPE_POPUP_MENU";
