[package]
name = "panel"
version = "0.1.0"
authors = ["veasnama <maveasnalearntosolve@gmail>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced_wgpu = {git = "https://github.com/koompi/iced.git", branch="winit_strut"}
iced_winit = {git = "https://github.com/koompi/iced.git", branch="winit_strut"}
env_logger = "0.8.3"
pollster = "0.2.1"
wgpu-subscriber = "0.1.0"
futures = "*"
