[package]
name = "desktop"
version = "0.1.0"
authors = ["leang27 <hangleang127@gmail.com>"]
edition = "2018"
description = "Desktop GUI for KOOMPI OS"
license = "MIT"
repository = "https://github.com/koompi/koompi-desktop"
readme = "README.md"
keywords = ["gui", "ui", "desktop", "shell", "desktop-shell"]
categories = ["gui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced_winit = { git = "https://github.com/veasnama/iced.git", branch = "iced_intergration" }
iced_wgpu = { git = "https://github.com/veasnama/iced.git", branch = "iced_intergration" }
version-compare = "0.0.11"
regex = "1.4.3"
failure = "0.1.8"
freedesktop_entry_parser = "1.1.1"